// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZ4UdoIqpOj9rZQ7yQMtP_L4Caj-KDHY',
    appId: '1:521080617106:web:ff152a0bf939bfb4c98e4b',
    messagingSenderId: '521080617106',
    projectId: 'e-commerce-4efb0',
    authDomain: 'e-commerce-4efb0.firebaseapp.com',
    storageBucket: 'e-commerce-4efb0.firebasestorage.app',
    measurementId: 'G-R2ZNG915F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvjItLQ7jgusOCUCkCMnURWFyMQXi0B0',
    appId: '1:521080617106:android:c999f194e603ad5bc98e4b',
    messagingSenderId: '521080617106',
    projectId: 'e-commerce-4efb0',
    storageBucket: 'e-commerce-4efb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdDYby531WGQ8s57vgbGB7A9ME0xlmnaQ',
    appId: '1:521080617106:ios:1e97ca62bb1e3854c98e4b',
    messagingSenderId: '521080617106',
    projectId: 'e-commerce-4efb0',
    storageBucket: 'e-commerce-4efb0.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdDYby531WGQ8s57vgbGB7A9ME0xlmnaQ',
    appId: '1:521080617106:ios:1e97ca62bb1e3854c98e4b',
    messagingSenderId: '521080617106',
    projectId: 'e-commerce-4efb0',
    storageBucket: 'e-commerce-4efb0.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvZ4UdoIqpOj9rZQ7yQMtP_L4Caj-KDHY',
    appId: '1:521080617106:web:0b75afaec0a6b7a1c98e4b',
    messagingSenderId: '521080617106',
    projectId: 'e-commerce-4efb0',
    authDomain: 'e-commerce-4efb0.firebaseapp.com',
    storageBucket: 'e-commerce-4efb0.firebasestorage.app',
    measurementId: 'G-SP76R5RE28',
  );
}
